version: '3.8'

services:
  samplebackend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 5193:80
      - 7193:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  yarp-proxy:
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - 5010:80
      - 7010:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  consul:
    container_name: Consul
    ports:
      - 8500:8500
      - 8600:8600/udp
    command: >
      agent -dev -server -ui -node=server-1 -bootstrap-expect=1
        -client="0.0.0.0"